(function(a,u,p){function J(d,c){var b=d.protocol[r](0,-1),a=d[q],e=d.hostname,C=/^https?$/.test(b),D=K[e.replace("www.","")],k=(a.match(L)||[""]).pop()[E](),n=k?~",mp3,mp4,wma,mov,avi,wmv,mkv,eot,woff,ttf,txt,csv,tsv,pdf,doc,docx,xls,xlsx,ppt,pptx,zip,tar,tgz,bz2,gz,rar,dmg,pkg,7z,ida,exe,sh,bat,"[v](","+k+","):0;f.trackOutbound&&C&&!~e[v](p.hostname)&&l(d,y,function(){h(0,"outbound",e,a,c);D&&h(1,D,"outbound",a)});f.trackDownloads&&n&&l(d,y,function(){h(0,"download",k,a)});f.trackActions&&!C&&l(d,
y,function(){h(0,b,a[r](b[m]+1).split("?")[0],p[q])})}function M(a,c){l(a,"submit",function(){for(var b=a.elements,g=0,e;g<b[m];)e=b[g++],e.name&&h(0,"form",a[z]("name")||a[z]("id")||"form "+c,e.name+":"+(e.type||e.tagName))})}function n(){n.a=n.a||0;var d={click:0,message:0},c,b;9>n.a++&&(a.twttr&&a.twttr.ready?a.__twitterIntentHandler||(l(a,w,function(g){try{"twitter.com"==g.origin[A](-11)&&g.data&&(b=a.JSON&&a.JSON.parse(g.data))&&"trigger"==b.method&&b.params&&(c=b.params[0],c in d||h(1,"Twitter",
c,p[q]))}catch(e){}}),a.twttr.ready(function(a){for(c in d)a.events.bind(c,function(){})}),a.__twitterIntentHandler=!0):setTimeout(n,5E3))}function t(){function d(c){h(1,"Facebook",c,p[q])}t.a=t.a||0;if(9>t.a++){var c=a.FB;if(c=c&&c.Event&&c.Event.subscribe)try{c("edge.create",function(){d("like")}),c("edge.remove",function(){d("unlike")}),c(w+".send",function(){d(w)})}catch(b){}else setTimeout(t,5E3)}}function N(){function d(c,b){var d=["cb_onsuccess",b,+new Date].join("_");c.onsuccess=(c.onsuccess?
c.onsuccess+",":"")+d;a[d]=function(){h(1,"LinkedIn",b,p[q])}}for(var c=u[F]("SCRIPT"),b=c[m],g=0,e,f;g<b;)e=c[g++],f=(e[z]("type")||"")[E](),!f[v]("in/")&&d(e,f[A](3))}function O(){function d(c,b){l(c,"load",function(){h(1,b,"status","logged in")});c.src=G[b]}var c=0,b;for(b in G)d(new Image(1,1),b);a.FB&&a.FB.getLoginStatus&&l(a,w,function(b){try{"facebook.com"==b.origin[A](-12)&&b.data&&~b.data[v]("xd_action=proxy_ready")&&a.FB.getLoginStatus(function(b){b&&"unknown"!==b.status&&!c++&&h(1,"Facebook",
"status","logged in")})}catch(d){}})}function P(){function d(){h(0,"print",u.title,p[q])}var c=a.matchMedia;(c=c&&c("print"))&&c.addListener(d);l(a,"afterprint",d)}function l(a,c,b){a[H]?a[H](c,b,!1):a.attachEvent("on"+c,b)}function h(d){var c=Array.prototype[r].call(arguments,0),b;c[0]=c[0]?B:"event";a[x]&&"function"==typeof a[x]&&(b=a[x].getAll&&a[x].getAll())&&k(b,"send",c);b=c;var g=a.TagLoader,e=a.s,f=[],h=1;if(g&&e&&e instanceof g){for(;h<b[m];h++)g="prop"+h,f.push(g),e[g]=b[h];e.linkTrackEvents=
"None";e.linkTrackVars=f.join(",");k([e],"tl",[e,"download"==b[1]?"d":"o",b[0]])}b=[].concat(c);B==b[0]&&(b[1]=B+":"+b.splice(2,1,b[1])[0]);b=b[r](1);k([a],"ClickTaleEvent",[b.join(":")]);k([a],"__utmTrackEvent",b);a._hmt&&k([a._hmt],"push",[["_trackEvent"].concat(b)]);if(a._gat||a._gaq)b=a._gat&&a._gat._getTrackers&&a._gat._getTrackers(),c[0]={social:"_trackSocial",event:"_trackEvent"}[c[0]],b?k(b,c[0],c[r](1)):a._gaq&&k([a._gaq],"push",[c])}function k(d,c,b){var g=0,e;for(f.debugMode&&a.console&&
a.console.log(c,b);g<d[m];)e=d[g++],e[c]&&"function"==typeof e[c]&&e[c].apply(e,b)}var I={trackTwitter:1,trackFacebook:1,trackLinkedIn:1,trackDownloads:1,trackOutbound:1,trackForms:1,trackUsers:1,trackActions:1,trackPrint:1,debugMode:0},K={"plus.google.com":"Google+","plus.url.google.com":"Google+","blogspot.com":"Blogger","facebook.com":"Facebook","on.fb.me":"Facebook","fb.me":"Facebook","fb.com":"Facebook","twitter.com":"Twitter","t.co":"Twitter","linkedin.com":"LinkedIn","myspace.com":"MySpace",
"vk.com":"VKontakte","odnoklassniki.ru":"Odnoklassniki","xing.com":"Xing","youtube.com":"YouTube","youtu.be":"YouTube","twoo.com":"Twoo","reddit.com":"Reddit","pinterest.com":"Pinterest","digg.com":"Digg","4sq.com":"Foursquare","foursquare.com":"Foursquare","hi.baidu.com":"Baidu Space"},G={Google:"https://accounts.google.com/CheckCookie?continue=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&amp;followup=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&amp;chtml=LoginDoneHtml&amp;checkedDomains=youtube&amp;checkConnection=youtube%3A291%3A1",
"Google+":"//plus.google.com/up/?continue=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png",Twitter:"//twitter.com/login?redirect_after_login=https%3A%2F%2Fplatform.twitter.com%2Fwidgets%2Fimages%2Fbtn.png"},L=/\.([0-9a-z]+)(?:[\?#]|$)/i,x=a.GoogleAnalyticsObject||"ga",f=a._ega||a._komito||{},m="length",r="slice",q="href",z="getAttribute",F="getElementsByTagName",v="indexOf",A="substr",E="toLowerCase",H="addEventListener",w="message",y="mousedown",B="social";(function(){var a=
0,c=u[F]("A"),b;for(b in I)b in f||(f[b]=I[b]);for(;a<c[m];)J(c[a++],a);if(f.trackForms)for(c=u.forms,a=0;a<c[m];)M(c[a++],a);f.trackTwitter&&n();f.trackFacebook&&t();f.trackLinkedIn&&N();f.trackUsers&&O();f.trackPrint&&P()})()})(window,document,location);
