(function(c,p,q){function K(d,a){var b=d.protocol[r](0,-1),e=d[t],c=d.hostname,h=/^https?$/.test(b),F=L[c.replace("www.","")],A=(e.match(M)||[""]).pop()[G](),N=A?~",mp3,mp4,wma,mov,avi,wmv,mkv,eot,woff,ttf,txt,csv,tsv,pdf,doc,docx,xls,xlsx,ppt,pptx,zip,tar,tgz,bz2,gz,rar,dmg,pkg,7z,ida,exe,sh,bat,"[x](","+A+","):0;k.trackOutbound&&h&&!~c[x](q.hostname)&&f(d,B,function(){l(0,"outbound",c,e,a);F&&l(1,F,"outbound",e)});k.trackDownloads&&N&&f(d,B,function(){l(0,"download",A,e)});k.trackActions&&!h&&f(d,
B,function(){l(0,b,e[r](b[m]+1).split("?")[0],q[t])})}function O(d,a){f(d,"submit",function(){for(var b=d.elements,e=0,c;e<b[m];)c=b[e++],c.name&&l(0,"form",d[C]("name")||d[C]("id")||"form "+a,c.name+":"+(c.type||c.tagName))})}function u(){u.a=u.a||0;var d={click:0,message:0},a,b;9>u.a++&&(c.twttr&&c.twttr.ready?c.__twitterIntentHandler||(f(c,y,function(e){try{"twitter.com"==e.origin[D](-11)&&e.data&&(b=c.JSON&&c.JSON.parse(e.data))&&"trigger"==b.method&&b.params&&(a=b.params[0],a in d||l(1,"Twitter",
a,q[t]))}catch(g){}}),c.twttr.ready(function(b){for(a in d)b.events.bind(a,function(){})}),c.__twitterIntentHandler=!0):setTimeout(u,5E3))}function v(){function d(a){l(1,"Facebook",a,q[t])}v.a=v.a||0;if(9>v.a++){var a=c.FB;if(a=a&&a.Event&&a.Event.subscribe)try{a("edge.create",function(){d("like")}),a("edge.remove",function(){d("unlike")}),a(y+".send",function(){d(y)})}catch(b){}else setTimeout(v,5E3)}}function P(){function d(a,b){var d=["cb_onsuccess",b,+new Date].join("_");a.onsuccess=(a.onsuccess?
a.onsuccess+",":"")+d;c[d]=function(){l(1,"LinkedIn",b,q[t])}}for(var a=w("SCRIPT"),b=a[m],e=0,g,h;e<b;)g=a[e++],h=(g[C]("type")||"")[G](),!h[x]("in/")&&d(g,h[D](3))}function Q(){function d(a,b){f(a,"load",function(){l(1,b,"status","logged in")});a.src=H[b]}var a=0,b;for(b in H)d(new Image(1,1),b);c.FB&&c.FB.getLoginStatus&&f(c,y,function(b){try{"facebook.com"==b.origin[D](-12)&&b.data&&~b.data[x]("xd_action=proxy_ready")&&c.FB.getLoginStatus(function(b){b&&"unknown"!==b.status&&!a++&&l(1,"Facebook",
"status","logged in")})}catch(d){}})}function R(){function d(){l(0,"print",p.title,q[t])}var a=c.matchMedia;(a=a&&a("print"))&&a.addListener(d);f(c,"afterprint",d)}function S(){function d(a){g=a.target||a.srcElement;h=g.currentSrc||g.src;l(0,g.tagName+":html5",a.type,h)}for(var a=T("AUDIO","VIDEO"),b=a[m]>>>0,c=0,g,h;c<b;)g=a[c++],f(g,"ended",d),f(g,"pause",d),f(g,"play",d);U()}function U(){function d(a){f=a.target||a.srcElement;l(0,"video:youtube",k[a.data],f.getVideoUrl())}for(var a=w("IFRAME"),
b=a[m],e=0,g=/(https?:)?(www\.)?youtube\.com\/embed/,h=[],k=["finish","play","pause"],f;e<b;)f=a[e++],g.test(f.src)&&h.push(f);if(b=h[m])c.onYouTubePlayerAPIReady=function(){for(e=0;e<b;)new c.YT.Player(h[e++],{events:{onStateChange:d},playerVars:{enablejsapi:1}})},c.YT||(w("HEAD")[0].appendChild(p.createElement("SCRIPT")).src="//www.youtube.com/iframe_api")}function V(){var d=0,a=p.documentElement,b,e;f(c,"scroll",function(){b=(a.scrollTop+p.body.scrollTop)/(a.scrollHeight-a.clientHeight)*100;e=
25*~~(b/25);d!=e&&(d=e,l(0,"scroll","depth",d))})}function f(d,a,b){d[I]?d[I](a,b,!1):d.attachEvent("on"+a,b)}function l(d){var a=Array.prototype[r].call(arguments,0),b;a[0]=a[0]?E:"event";c[z]&&"function"==typeof c[z]&&(b=c[z].getAll&&c[z].getAll())&&n(b,"send",a);b=a;var e=c.TagLoader,g=c.s,h=[],f=1;if(e&&g&&g instanceof e){for(;f<b[m];f++)e="prop"+f,h.push(e),g[e]=b[f];g.linkTrackEvents="None";g.linkTrackVars=h.join(",");n([g],"tl",[g,"download"==b[1]?"d":"o",b[0]])}b=[].concat(a);E==b[0]&&(b[1]=
E+":"+b.splice(2,1,b[1])[0]);b=b[r](1);n([c],"ClickTaleEvent",[b.join(":")]);n([c],"__utmTrackEvent",b);c._hmt&&n([c._hmt],"push",[["_trackEvent"].concat(b)]);if(c._gat||c._gaq)b=c._gat&&c._gat._getTrackers&&c._gat._getTrackers(),a[0]={social:"_trackSocial",event:"_trackEvent"}[a[0]],b?n(b,a[0],a[r](1)):c._gaq&&n([c._gaq],"push",[a])}function n(d,a,b){var e=d[m]>>>0,g=0,f;for(k.debugMode&&c.console&&c.console.log(a,b);g<e;)f=d[g++],f[a]&&"function"==typeof f[a]&&f[a].apply(f,b)}function T(d){for(var a=
[],b=Array.prototype[r].call(arguments,0),c=0,c=0;c<b[m];)a.push.apply(a,w(b[c++]));return a}function w(c){return p.getElementsByTagName(c)}var J={trackTwitter:1,trackFacebook:1,trackLinkedIn:1,trackDownloads:1,trackOutbound:1,trackForms:1,trackUsers:1,trackActions:1,trackPrint:1,trackMedia:1,trackScroll:1,debugMode:0},L={"plus.google.com":"Google+","plus.url.google.com":"Google+","blogspot.com":"Blogger","facebook.com":"Facebook","on.fb.me":"Facebook","fb.me":"Facebook","fb.com":"Facebook","twitter.com":"Twitter",
"t.co":"Twitter","linkedin.com":"LinkedIn","myspace.com":"MySpace","vk.com":"VKontakte","odnoklassniki.ru":"Odnoklassniki","xing.com":"Xing","youtube.com":"YouTube","youtu.be":"YouTube","twoo.com":"Twoo","reddit.com":"Reddit","pinterest.com":"Pinterest","digg.com":"Digg","4sq.com":"Foursquare","foursquare.com":"Foursquare","hi.baidu.com":"Baidu Space"},H={Google:"https://accounts.google.com/CheckCookie?continue=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&amp;followup=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&amp;chtml=LoginDoneHtml&amp;checkedDomains=youtube&amp;checkConnection=youtube%3A291%3A1",
"Google+":"//plus.google.com/up/?continue=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png",Twitter:"//twitter.com/login?redirect_after_login=https%3A%2F%2Fplatform.twitter.com%2Fwidgets%2Fimages%2Fbtn.png"},M=/\.([0-9a-z]+)(?:[\?#]|$)/i,z=c.GoogleAnalyticsObject||"ga",k=c._ega||c._komito||{},m="length",r="slice",t="href",C="getAttribute",x="indexOf",D="substr",G="toLowerCase",I="addEventListener",y="message",B="mousedown",E="social";(function(){var c=0,a=w("A"),b=a[m],
e;for(e in J)e in k||(k[e]=J[e]);for(;c<b;)K(a[c++],c);if(k.trackForms)for(a=p.forms,b=a[m],c=0;c<b;)O(a[c++],c);k.trackTwitter&&u();k.trackFacebook&&v();k.trackLinkedIn&&P();k.trackUsers&&Q();k.trackPrint&&R();k.trackMedia&&S();k.trackScroll&&V()})()})(window,document,location);
